export { default as Navbar } from "./Navbar";
export { default as Hero } from "./Hero";
export { default as Newsletter } from "./Newsletter";
export { default as Boxes } from "./Boxes";
export { default as Learn } from "./Learn";
export { default as FQA } from "./FQA";
export { default as Instructors } from "./Instructors";
export { default as Contact } from "./Contact";
export { default as Footer } from "./Footer";
